carpeta para la pagina estrenos
VeroS04/movie-app pull request #6
Opened 2023-02-27 00:10 UTC by VeroS04

2023-03-13 00:49 UTC, adrianmdp approved these changes

2023-03-13 01:03 UTC, adrianmdp requested changes

2023-03-13 01:03 UTC, adrianmdp commented on src/components/common/upcoming-page/index.tsx
> +    <div className="list-page">
Este código se repite en los componentes UpcomingPage y PopularesList. Podrías tener un componente reutilizable que se llame GridMovies por ejemplo que utilices en las pages Upcoming y Populares

2023-03-13 16:21 UTC, VeroS04 reviewed
puedo crear dos carpetas para las cards que se usan en las paginas particulares y las que se usan en home que llevan un scroll horizontal

2023-03-15 01:54 UTC, adrianmdp requested changes

2023-03-15 01:54 UTC, adrianmdp commented on src/components/common/gridMovies/index.tsx
> +export type Movies = {
Cuando se tipan las props de un componente, se le suele poner Props al type
```javascript
type Props = {
   movies: Movie[],
   text?: string
}
const GridMovies: FC<Props> = ({ ..... }) => {
```
Además no deberías exportarlo xq las props solo se utilizan en este componente.

2023-03-15 01:54 UTC, adrianmdp commented on src/components/common/pageMovies/index.tsx
> +const PageMovie: FC<Movies> = ({ movies, text }) => {
Este componente deberías eliminarlo xq ya creaste GridMovies.
Si ya tenes una carpeta de pages, no crees en componentes componentes page. Esto eliminalo directamente y donde estas usandolo, reemplaza por GridMovies.

2023-03-15 01:54 UTC, adrianmdp commented on src/components/common/populares-home/index.tsx
> +export type MoviePoster = {
Acá lo mismo que antes, cambialo por Props

2023-03-15 01:54 UTC, adrianmdp commented on src/components/common/populares-page/index.tsx
> +export type MoviePopular = {
Mismo que arriba

2023-03-15 01:54 UTC, adrianmdp commented on src/pages/home/index.tsx
> +      <PopularesList movies={popular} text={"Populares"} />
Acá tenés el mismo caso que GridMovies.
Lo ideal es que tengas un componente ListMovies o como quieras llamarlo que en un caso le pases popular y en el otro top.
El mismo componente debería renderizar diferente contenido.

2023-03-15 01:54 UTC, adrianmdp commented on src/pages/new-releases/index.tsx
> +      <PageMovie movies={movies} text={"Upcoming Movies"} />
Acá usa GridMovies que era el objetivo al crearla.

2023-03-20 00:03 UTC, adrianmdp commented on src/components/common/gridMovies/index.tsx
> +export type Movies = {
En la nueva PR que te voy a subir hice algunos cambios en tu código.

2023-03-20 00:13 UTC, adrianmdp approved these changes

2023-03-20 00:14 UTC, merged